site_name: "计算机技术分享：中国速度"
site_url: "https://china-speed.org.cn/"
site_favicon: "/favicon.ico"
repo_url: https://github.com/china-speed/china-speed.github.io/
edit_uri: edit/mkdocs/
copyright: <a rel="nofollow" href="http://www.beian.miit.gov.cn">沪ICP备19045595号-2</a>
google_analytics: ['UA-155057169-1', 'china-speed.org.cn']
nav:
    - "China Speed": "README.md"
