name: CI

on:
  push:
    branches:
    - mkdocs

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: build docs to HTML
      env:
        CUSTOM_DOMAIN: china-speed.org
      run: | 
        sudo apt-get update
        sudo apt-get install -y python-pip
        sudo -H pip install mkdocs
        ./build-docs.sh
        echo $CUSTOM_DOMAIN > site/CNAME
        ls -l ./site
        
    - name: deploy to gh-pages
      uses: crazy-max/ghaction-github-pages@v1
      with:
        target_branch: master
        build_dir: site
      env:
        GITHUB_PAT: ${{ secrets.GIT_TOKEN }}
